name: iOS Build Check

on:
  push:
    branches: [ main, feature/video-notes ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Unit Tests
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@385a8ecc719e50b8c71af6ab01a624b486b7c3bc
        with:
          persist-credentials: false

      - name: Setup environment
        run: source ci_scripts/ci_common.sh && setup_github_actions_environment

      - name: Run Build and Unit Tests
        run: swift run -q tools ci unit-tests
